#
# https://circleci.com/developer/ja/orbs/orb/circleci/node
#
version: 2.1

orbs:
  node: circleci/node@7.0.0

jobs:
  test:
    docker:
      - image: cimg/node:22.12

    steps:
      - checkout
      - node/install-packages
      - run:
          name: "Run tests"
          command: npm run test

workflows:
  test-workflow:
    jobs:
      - test
